a=int(input("enter real part 1st number:"))
b=int(input("enter imaginary part of 1st number:"))
c=int(input("enter real part of 2nd number:"))
d=int(input("enter imaginary part of 2nd number:"))
z1=complex(a,b)
z2=complex(c,d)
print("addition of complex numbers:",(z1+z2))
print("product of complex numbers:",(z1*z2))